[tool.black]
line-length = 88
target-version = ['py37', 'py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_first_party = ["inspect_spacy_model"]
skip_glob = [
    "*/venv/*",
    "*/.venv/*", 
    "*/env/*",
    "*/spacy-env/*",
    "*/build/*",
    "*/dist/*"
]
